### ISSUE TITLE
UART wiring?

### ISSUE THREAD

**Issue by DennisGaida** [ma-lwa-re/dreamdesk#1]
This project looks very promising and clean. I couldn't find any documentation on how to do the UART wiring since the desks themselves don't have a UART ports AFAIK? Where are the pins configured?

I'm particularly interested in what you are doing with Logicdata (https://github.com/ma-lwa-re/dreamdesk/blob/master/main/logicdata.c), since the protocol seems well established when looking at the code and the other decoded versions of the protocol I could find (e.g. https://github.com/phord/RoboDesk) aren't as complete.

Do you have any hardware / wiring specs / photos on how to set this up per supported desk model?

**Comment by ma-lwa-re** [comment]
Hi Dennis!

Thank you for your interest in this project.

You're right, the desk itself doesn't have a UART port. The communication from the desk to the supplied remote control is done through a Mini-Fit Jr. 2x2 connector. You can find a pretty detailed writeup about the project here:

- https://ma.lwa.re/dreamdesk

The protocol used (LIN) is explained, as well as the reversing steps. The hardware section of the page describes what chips and development cards have been used first for the PoC, and then the design of a custom board to extend the existing remote control.

Hope this will help, otherwise, I'll be more than happy to give you more details about the implementation.

**Comment by DennisGaida** [comment]
I totally didn't see the link in the sidebar - I only checked the README. Really awesome what you have done with the logic analyzer and digging into the protocol(s)!

The accompanying blog post explains everything very well, unfortunately a bit too complicated for me with the additional ATA663211 module and custom PCB. Also I don't think you are man-in-the-middling the existing hardware buttons, i.e. do they still work? Out of pure interest: How come you have so many different desks (IKEA, LogicData etc.)?

I'm currently doing my own implementation of desk automation based on previous work and the interface is a lot more "simple" - just connect the wires to the GPIO pins of the Arduino: https://github.com/DennisGaida/RoboDesk If I can figure out how to map your sophisticated UART implementation onto GPIO headers and digital writes, I might be able to use your awesome decoded protocol.

**Comment by ma-lwa-re** [comment]
You're right, in this project I'm not doing a MITM but using my own controller to directly exchange with the existing desk hardware. However, note that Logicdata has two controllers technologies:

1. The slightly older CONTROL BOX (SMARTneo or COMPACTneo) that uses the HS port that you can interface and wire to a Raspberry, Arduino, or any custom board directly.
2. The more recent DYNAMIC MOTION system (DMPHub) that uses the LIN protocol to interact with the components.

The idea of this project is to support all desks that are using the LIN protocol, that's why it currently supports IKEA, Logicdata (DYNAMIC MOTION), and hopefully many more soon 🙂.

So in your case, you will have to interface your Arduino with the desk DIN 7 plug according to this schematic:

- https://github.com/DennisGaida/RoboDesk/blob/master/schematic/v2/schematic.pdf

**Comment by DennisGaida** [comment]
Dang, you really looked into this. Love the details! Yes, I was totally referring to the older control boxes (my desk is a couple of years old). Its very good information that there is a new system using the LIN protocol that is used by more desks.
